### ISSUE TITLE
楼主，你写的canvas截图的demo，为什么不能截gif图呢？截出来是空

### ISSUE THREAD

**Issue by pcjgithub** [Aaaaaaaty/Blog#18]

**Comment by Aaaaaaaty** [comment]
@pcjgithub 原因大概是canvas的drawImage这个api不能直接绘制gif这种多帧的动态图

**Comment by pcjgithub** [comment]
哦哦，现在我们有个需求要做一个类似QQ截图功能的东西，这个可以给一个demo或者思路或者技术文档吗

**Comment by pcjgithub** [comment]
我自己确实不知道用什么技术才能集成那些功能，比如截图之后可以移动，截视频等多阵图

**Comment by Aaaaaaaty** [comment]
@pcjgithub canvas目前静态图应该是可以的 但是gif和svg可能会出现些问题。截图移动纯代码就可以控制你的截图框，截视频的话我不确定canvas2html里面绘制video标签出来的效果，如果可以绘制出某一帧，那么也许可以当你截图的时候自动暂停播放去绘制。总的来说截图需要基于html2canvas 你可以看看它的文档，什么东西可以从html转换为canvas 剩下截取的部分就很容易了
